title: Stackbit App Theme
baseURL: /
params:
  layout_type: full-width
  style: minimal
  palette: blue
  mode: light
  base_font: sans-serif
  header:
    title: App
    logo: images/logo1-h-k7f8ixth-1.png
    logo_alt: App logo
    has_primary_nav: false
    primary_nav_links:
      - label: Pricing
        url: /pricing
        style: link
      - label: About
        url: /about
        style: link
      - label: Blog
        url: /blog
        style: link
      - label: Style Guide
        url: /style-guide
        style: link
    has_secondary_nav: true
    secondary_nav_links:
      - label: Home
        url: /
        style: primary
      - label: Upcoming courses
        url: /pricing
        style: secondary
      - label: Contact
        url: /about
        style: primary
        has_icon: false
        icon: arrow-right
        icon_position: right
        new_window: false
        no_follow: false
    has_anncmnt: false
    anncmnt_content: >-
      Curabitur ac tellus mattis, tempor ipsum eu, eleifend sapien. **[Learn
      More](/pricing/)**
    anncmnt_align: left
    anncmnt_is_home_only: true
    anncmnt_has_close: true
    anncmnt_id: new-features
  domain: 'https://best-spider-bdcb6.netlify.app'
  footer:
    logo_alt: lorem-ipsum
    has_primary_nav: true
    primary_nav_title: lorem-ipsum
    primary_nav_links: []
    has_secondary_nav: true
    secondary_nav_title: lorem-ipsum
    secondary_nav_links: []
    has_tertiary_nav: true
    tertiary_nav_title: lorem-ipsum
    tertiary_nav_links: []
    has_social: true
    social_links: []
    content: lorem-ipsum
    links: []
    logo: images/logo1-h-k7f8ixth-1.png
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
